remove uesless import
silenceper/xfsquota pull request #2
Opened 2023-03-15 11:07 UTC by Wang-Kai

2023-03-15 13:30 UTC, silenceper requested changes

2023-03-15 13:30 UTC, silenceper commented on pkg/xfsquota/quota.go
> -	"strconv"
这个不是有在使用吗？

2023-03-16 01:35 UTC, Wang-Kai commented on pkg/xfsquota/quota.go
> -	"strconv"
”strconv“ 仅是挪了个位置，编辑器自动格式化的。

import C 没有在用

2023-03-16 06:54 UTC, silenceper commented on pkg/xfsquota/quota.go
> -	"strconv"
好的

2023-03-16 06:54 UTC, merged